import os
import json
import logging
from typing import Dict, Any, List
from config import settings

logger = logging.getLogger(__name__)

# llm_engine.py - LLM-less Safe Version
GROQ_API_KEY = getattr(settings, 'GROQ_API_KEY', None)
LLM_AVAILABLE = bool(GROQ_API_KEY and GROQ_API_KEY.strip() and "placeholder" not in GROQ_API_KEY.lower())

client = None
MODEL = "llama3-70b-8192"

if LLM_AVAILABLE:
    try:
        from groq import Groq
        client = Groq(api_key=GROQ_API_KEY)
        logger.info("✅ LLM (Groq) initialized successfully.")
    except Exception as e:
        logger.error(f"Groq init failed: {e}")
        LLM_AVAILABLE = False
else:
    logger.info("⚠️ Running in LLM-less (Rule-Based) mode.")

def _invoke_llm(prompt: str, max_tokens: int = 1000, temperature: float = 0.2, expect_json: bool = False, fallback_value=None):
    """Central router for all LLM calls to guarantee safe execution."""
    if not LLM_AVAILABLE or not client:
        return fallback_value

    try:
        response = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model=MODEL,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        content = response.choices[0].message.content.strip()
        
        if expect_json:
            if content.startswith("```json"):
                content = content[7:-3]
            elif content.startswith("```"):
                content = content[3:-3]
            return json.loads(content)
            
        return content
    except Exception as e:
        logger.error(f"LLM Invocation Error: {str(e)}")
        return fallback_value


def generate_executive_summary(score: int, weaknesses: List[str], strengths: List[str], case_data: Dict[str, Any]) -> str:
    """Takes deterministic outputs from the rule engines and generates a summary."""
    if not LLM_AVAILABLE:
        return f"Case Score: {score}/100. {'Strong case.' if score >= 70 else 'Moderate risk.' if score >= 45 else 'High risk - review defects.'}"

    prompt = f"""
    You are a Senior Litigation Partner at a top-tier law firm.
    Review the following case parameters generated by our deterministic rule engines.
    
    Case Score: {score}/100
    Role: {case_data.get('client_role', 'Unknown')}
    Case Type: {case_data.get('case_type', 'Unknown')}
    
    Identified Strengths:
    {chr(10).join(['- ' + s for s in strengths]) if strengths else 'None'}
    
    Identified Weaknesses & Risks:
    {chr(10).join(['- ' + w for w in weaknesses]) if weaknesses else 'None'}
    
    Generate a concise, authoritative 2-paragraph executive summary of this case. 
    Do NOT recalculate the score or dispute the weaknesses. Just explain the strategic 
    posture, highlighting the main risks and the overall strength of the case.
    Use a professional, objective legal tone.
    """

    fallback = f"Case Score: {score}/100. {'Strong case.' if score >= 70 else 'Moderate risk.' if score >= 45 else 'High risk - review defects.'}"
    return _invoke_llm(prompt, max_tokens=300, temperature=0.3, fallback_value=fallback)


def enhance_legal_draft(base_draft: str, draft_type: str, case_data: Dict[str, Any], tone: str = "Standard") -> str:
    if not LLM_AVAILABLE:
        return base_draft

    prompt = f"""
    You are an expert appellate litigator and draftsman.
    I have a raw, structural template draft for a '{draft_type}'.
    
    Client Role: {case_data.get('client_role', 'Unknown')}
    Case Type: {case_data.get('case_type', 'Unknown')}
    Requested Tone: {tone} (Ensure the draft strictly adheres to this tone: Standard=Professional, Aggressive=Firm/Threatening, Conciliatory=Negotiable/Polite).

    Here is the structural draft:
    {base_draft}
    
    Task:
    Rewrite and polish this draft to make it sound like it was written by a top-tier senior advocate.
    Do NOT change the core facts, dates, or amounts.
    Improve the flow, add standard legal formalisms, and make the arguments more persuasive.
    Return ONLY the final text of the legal draft, without any preamble or explanation. Keep the formatting clean.
    """

    return _invoke_llm(prompt, max_tokens=2000, temperature=0.4, fallback_value=base_draft)

def extract_fact_graph(text: str) -> Dict[str, Any]:
    if not LLM_AVAILABLE:
        return None

    prompt = f"""
    You are an expert legal AI capable of mapping facts.
    Extract a structured Fact Graph from the following case description:
    
    "{text}"
    
    Return a JSON object strictly following this structure:
    {{
        "entities": ["entity1", "entity2"],
        "relationships": [
            {{"source": "entity1", "target": "entity2", "relation": "description"}}
        ],
        "contradictions": [
            "description of contradiction 1"
        ],
        "timeline_complexity": "High/Medium/Low"
    }}
    Do not output any markdown formatting, just raw JSON.
    """

    return _invoke_llm(prompt, max_tokens=1000, temperature=0.1, expect_json=True, fallback_value=None)


def analyze_precedent_relationships(case_data: Dict[str, Any], precedents: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not LLM_AVAILABLE:
        return None
        
    if not precedents:
        return []

    prec_context = ""
    for idx, p in enumerate(precedents):
        prec_context += f"Precedent {idx+1}: {p.get('title', 'Unknown')} - {p.get('summary', 'No summary')}\n"

    prompt = f"""
    Analyze the relationship between the following case facts and the precedents.
    
    Case Facts:
    Role: {case_data.get('client_role', 'Unknown')}
    Details: {case_data.get('case_description', 'No description')}
    
    Precedents:
    {prec_context}
    
    For each precedent, determine if it is:
    - BINDING: Directly applicable and supports the case.
    - DISTINGUISHABLE: Facts are different enough that opposing counsel will distinguish it.
    - OVERRULED/DANGEROUS: High risk of relying on this.
    
    Return a JSON array of objects strictly following this structure:
    [
        {{
            "id": "index_of_precedent_starting_from_1",
            "relationship": "BINDING|DISTINGUISHABLE|OVERRULED",
            "reasoning": "1 sentence explanation"
        }}
    ]
    Do not output any markdown formatting, just raw JSON.
    """

    analysis = _invoke_llm(prompt, max_tokens=1000, temperature=0.2, expect_json=True, fallback_value=None)
    if not analysis:
        return precedents

    # Merge back
    try:
        for item in analysis:
            idx = int(item["id"]) - 1
            if 0 <= idx < len(precedents):
                precedents[idx]["relationship"] = item.get("relationship", "UNKNOWN")
                precedents[idx]["llm_reasoning"] = item.get("reasoning", "")
    except Exception as e:
        logger.error(f"Error merging precedent LLM reasoning: {e}")
        
    return precedents
