import os
import json
import logging
from typing import Dict, Any, List
from groq import Groq
from config import settings

logger = logging.getLogger(__name__)

# Initialize Groq client
# Fallback to empty string if not set, but config sets it from os.getenv
GROQ_API_KEY = settings.GROQ_API_KEY
client = Groq(api_key=GROQ_API_KEY)

# Use Llama 3 70B as the default model for complex legal reasoning
MODEL = "llama3-70b-8192"

def generate_executive_summary(score: int, weaknesses: List[str], strengths: List[str], case_data: Dict[str, Any]) -> str:
    """
    Takes deterministic outputs from the rule engines and generates a premium, 
    natural-language executive summary.
    """
    if not GROQ_API_KEY or GROQ_API_KEY == "gsk_6dIjjHfYhnzWb8CLHe8FWGdyb3FYzO2pnwJxEs69BYTawWTV1rL6_placeholder":
        return "LLM Copilot is currently disconnected. Please configure GROQ_API_KEY."

    prompt = f"""
    You are a Senior Litigation Partner at a top-tier law firm.
    Review the following case parameters generated by our deterministic rule engines.
    
    Case Score: {score}/100
    Role: {case_data.get('client_role', 'Unknown')}
    Case Type: {case_data.get('case_type', 'Unknown')}
    
    Identified Strengths:
    {chr(10).join(['- ' + s for s in strengths]) if strengths else 'None'}
    
    Identified Weaknesses & Risks:
    {chr(10).join(['- ' + w for w in weaknesses]) if weaknesses else 'None'}
    
    Generate a concise, authoritative 2-paragraph executive summary of this case. 
    Do NOT recalculate the score or dispute the weaknesses. Just explain the strategic 
    posture, highlighting the main risks and the overall strength of the case.
    Use a professional, objective legal tone.
    """

    try:
        response = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model=MODEL,
            temperature=0.3,
            max_tokens=300,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        logger.error(f"Groq API Error in summary generation: {str(e)}")
        return "Error generating AI summary. The case metrics above remain accurate."


def enhance_legal_draft(base_draft: str, draft_type: str, case_data: Dict[str, Any], tone: str = "Standard") -> str:
    """
    Takes the structural draft from the rule engines and uses the LLM to refine the language,
    add persuasive legal arguments, and apply the specific requested tone.
    """
    if not GROQ_API_KEY or GROQ_API_KEY == "gsk_6dIjjHfYhnzWb8CLHe8FWGdyb3FYzO2pnwJxEs69BYTawWTV1rL6_placeholder":
        return base_draft

    prompt = f"""
    You are an expert appellate litigator and draftsman.
    I have a raw, structural template draft for a '{draft_type}'.
    
    Client Role: {case_data.get('client_role', 'Unknown')}
    Case Type: {case_data.get('case_type', 'Unknown')}
    Requested Tone: {tone} (Ensure the draft strictly adheres to this tone: Standard=Professional, Aggressive=Firm/Threatening, Conciliatory=Negotiable/Polite).

    Here is the structural draft:
    {base_draft}
    
    Task:
    Rewrite and polish this draft to make it sound like it was written by a top-tier senior advocate.
    Do NOT change the core facts, dates, or amounts.
    Improve the flow, add standard legal formalisms, and make the arguments more persuasive.
    Return ONLY the final text of the legal draft, without any preamble or explanation. Keep the formatting clean.
    """

    try:
        response = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model=MODEL,
            temperature=0.4,
            max_tokens=2000,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        logger.error(f"Groq API Error in draft enhancement: {str(e)}")
        return base_draft

def extract_fact_graph(text: str) -> Dict[str, Any]:
    """
    Uses the LLM to extract entities, relationships, and contradictions,
    building a structured Fact Graph from the raw text.
    Returns None if LLM fails, triggering the deterministic fallback.
    """
    if not GROQ_API_KEY or GROQ_API_KEY == "gsk_6dIjjHfYhnzWb8CLHe8FWGdyb3FYzO2pnwJxEs69BYTawWTV1rL6_placeholder":
        return None

    prompt = f"""
    You are an expert legal AI capable of mapping facts.
    Extract a structured Fact Graph from the following case description:
    
    "{text}"
    
    Return a JSON object strictly following this structure:
    {{
        "entities": ["entity1", "entity2"],
        "relationships": [
            {{"source": "entity1", "target": "entity2", "relation": "description"}}
        ],
        "contradictions": [
            "description of contradiction 1"
        ],
        "timeline_complexity": "High/Medium/Low"
    }}
    Do not output any markdown formatting, just raw JSON.
    """

    try:
        response = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model=MODEL,
            temperature=0.1,
            max_tokens=1000,
        )
        content = response.choices[0].message.content.strip()
        if content.startswith("```json"):
            content = content[7:-3]
        return json.loads(content)
    except Exception as e:
        logger.error(f"Groq API Error in fact graph extraction: {str(e)}")
        return None


def analyze_precedent_relationships(case_data: Dict[str, Any], precedents: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Analyzes the relationship between the case facts and the retrieved precedents.
    Returns the enriched precedents with 'relationship' and 'reasoning' fields.
    Returns None if LLM fails.
    """
    if not GROQ_API_KEY or GROQ_API_KEY == "gsk_6dIjjHfYhnzWb8CLHe8FWGdyb3FYzO2pnwJxEs69BYTawWTV1rL6_placeholder":
        return None
        
    if not precedents:
        return []

    prec_context = ""
    for idx, p in enumerate(precedents):
        prec_context += f"Precedent {idx+1}: {p.get('title', 'Unknown')} - {p.get('summary', 'No summary')}\n"

    prompt = f"""
    Analyze the relationship between the following case facts and the precedents.
    
    Case Facts:
    Role: {case_data.get('client_role', 'Unknown')}
    Details: {case_data.get('case_description', 'No description')}
    
    Precedents:
    {prec_context}
    
    For each precedent, determine if it is:
    - BINDING: Directly applicable and supports the case.
    - DISTINGUISHABLE: Facts are different enough that opposing counsel will distinguish it.
    - OVERRULED/DANGEROUS: High risk of relying on this.
    
    Return a JSON array of objects strictly following this structure:
    [
        {{
            "id": "index_of_precedent_starting_from_1",
            "relationship": "BINDING|DISTINGUISHABLE|OVERRULED",
            "reasoning": "1 sentence explanation"
        }}
    ]
    Do not output any markdown formatting, just raw JSON.
    """

    try:
        response = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model=MODEL,
            temperature=0.2,
            max_tokens=1000,
        )
        content = response.choices[0].message.content.strip()
        if content.startswith("```json"):
            content = content[7:-3]
        analysis = json.loads(content)
        
        # Merge back
        for item in analysis:
            idx = int(item["id"]) - 1
            if 0 <= idx < len(precedents):
                precedents[idx]["relationship"] = item["relationship"]
                precedents[idx]["llm_reasoning"] = item["reasoning"]
                
        return precedents
    except Exception as e:
        logger.error(f"Groq API Error in precedent analysis: {str(e)}")
        return None

