import { ui } from '../../ui.js?v=8';

// UTILITIES MODULE
// ==========================================================================

/**
 * Escapes HTML characters to prevent XSS attacks when rendering user input.
 * @param {string} unsafe The untrusted string.
 * @returns {string} The sanitized string.
 */
function escapeHtml(unsafe) {
    if (typeof unsafe !== 'string') return unsafe;
    
    // Use DOMPurify if available for robust sanitization
    if (window.DOMPurify) {
        return window.DOMPurify.sanitize(unsafe, { ALLOWED_TAGS: [], ALLOWED_ATTR: [] });
    }
    
    // Fallback to basic escaping
    return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
         .replace(/'/g, "&#039;");
}

/**
 * Centralized API Error Handler.
 * Parses error objects/responses and displays user-friendly toast messages.
 * @param {Error|Response|string} error The error encountered.
 * @param {string} customMessage Optional user-friendly override message.
 */
function handleApiError(error, customMessage = "An unexpected error occurred.") {
    console.error("[JudiQ API Error]", error);
    
    let displayMessage = customMessage;
    
    // If it's a TypeError, it's likely a network failure (CORS, offline)
    if (error instanceof TypeError || error.message === 'Failed to fetch') {
        displayMessage = "Network Error: Could not reach the server. Please check your connection.";
    } 
    // If it's an HTTP error response passed directly
    else if (error && error.status) {
        if (error.status === 401 || error.status === 403) {
            displayMessage = "Authentication Error: Please log in again.";
        } else if (error.status >= 500) {
            displayMessage = "Server Error: The JudiQ engine encountered an internal failure.";
        }
    }
    // If it's a standard JS Error with a specific message
    else if (error instanceof Error && error.message) {
        // Only use the raw message if it's explicitly generated by our logic, else use customMessage
        if (error.message.includes("HTTP error")) {
            displayMessage = "Server returned an error. Please try again.";
        }
    }

    ui.toast(displayMessage, 'error');
}

// Attach to window so they can be accessed globally by script.js
export { escapeHtml };
export { handleApiError };




